name: click_click
description: Game of click.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  mobx: ^2.1.3
  objectbox: ^1.7.1
  flutter_mobx: ^2.0.6+5
  path_provider: ^2.0.11
  flutter_modular: ^5.0.3
  objectbox_flutter_libs: ^1.7.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  mobx_codegen: ^2.1.1
  objectbox_generator: ^1.7.1

  flutter_lints: ^2.0.0

objectbox:
  output_dir: app/data

flutter:

  uses-material-design: true
